// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import type * as Plugin from "@docusaurus/types/src/plugin";
import type * as OpenApiPlugin from "docusaurus-plugin-openapi-docs";
import 'dotenv/config';

const config: Config = {
  title: "AdGem",
  tagline: "AdGem Integrations Documentation",
  url: process.env.DOCUSAURUS_URL || 'https://adgem.github.io',
  baseUrl: process.env.DOCUSAURUS_BASE_URL || '/adgem-integrations-documentation/',
  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",
  favicon: "img/favicon.svg",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'adgem', // Usually your GitHub org/user name.
  projectName: 'adgem-integrations-documentation', // Usually your repo name.
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: require.resolve("./sidebars.ts"),
          docItemComponent: "@theme/ApiItem", // Derived from docusaurus-theme-openapi
          // plans/ are internal; offer.tag is a redundant generated tag-landing page
          // (we hand-arrange the Offer API sidebar, so the tag landing isn't used).
          exclude: ["plans/**", "reference/offer-api/offer.tag.mdx"],
          async sidebarItemsGenerator({defaultSidebarItemsGenerator, ...args}) {
            const items = await defaultSidebarItemsGenerator(args);
            // Filter out index docs from autogenerated sidebar items.
            // These docs are already used as category links in sidebars.ts,
            // so including them as child items creates self-referencing links.
            return items.filter((item) => {
              if (item.type === 'doc') {
                return !item.id.endsWith('/index');
              }
              return true;
            });
          },
        },
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig:
    {
      docs: {
        sidebar: {
          hideable: true,
        },
      },
      navbar: {
        title: "AdGem Integrations",
        logo: {
          alt: "AdGem Logo",
          src: "img/adgem-logo-white.svg",
        },
        // Five top-level surfaces (Gus' IA, PUB-191). Each links to its surface
        // landing; the scoped sidebar follows from the target doc automatically.
        items: [
          {
            label: "Get Started",
            position: "left",
            to: "/docs/get-started",
          },
          {
            label: "Integrate",
            position: "left",
            to: "/docs/integrate/overview",
          },
          {
            label: "Configure",
            position: "left",
            to: "/docs/configure",
          },
          {
            label: "Reference",
            position: "left",
            // Reference defaults to the Prism overview per Gus' v5 IA ("Prism is the
            // default landing"). The reference/index surface landing stays reachable
            // via the sidebar/breadcrumb. (PUB-191, WS1)
            to: "/docs/reference/prism/overview",
          },
          {
            label: "Resources",
            position: "left",
            to: "/docs/resources",
          },
          {
            href: "https://github.com/AdGem/adgem-integrations-documentation",
            label: "GitHub",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Evaluate",
            items: [
              { label: "For Decision Makers", to: "/for-decision-makers" },
            ],
          },
          {
            title: "More",
            items: [
              { label: "Service Status", href: "https://status.adgem.com" },
              { label: "Legal", href: "https://adgem.com/legal" },
              { label: "Support", href: "https://adgem.com/support" },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} <a href="https://adgem.com">AdGem</a>.`,
      },
      prism: {
        additionalLanguages: [
          "ruby",
          "csharp",
          "php",
          "java",
          "powershell",
          "json",
          "bash",
          "dart",
          "objectivec",
          "r",
        ],
      },
      languageTabs: [
        {
          highlight: "python",
          language: "python",
          logoClass: "python",
        },
        {
          highlight: "bash",
          language: "curl",
          logoClass: "curl",
        },
        {
          highlight: "csharp",
          language: "csharp",
          logoClass: "csharp",
        },
        {
          highlight: "go",
          language: "go",
          logoClass: "go",
        },
        {
          highlight: "javascript",
          language: "nodejs",
          logoClass: "nodejs",
        },
        {
          highlight: "ruby",
          language: "ruby",
          logoClass: "ruby",
        },
        {
          highlight: "php",
          language: "php",
          logoClass: "php",
        },
        {
          highlight: "java",
          language: "java",
          logoClass: "java",
          variant: "unirest",
        },
        {
          highlight: "powershell",
          language: "powershell",
          logoClass: "powershell",
        },
        {
          highlight: "dart",
          language: "dart",
          logoClass: "dart",
        },
        {
          highlight: "javascript",
          language: "javascript",
          logoClass: "javascript",
        },
        {
          highlight: "c",
          language: "c",
          logoClass: "c",
        },
        {
          highlight: "objective-c",
          language: "objective-c",
          logoClass: "objective-c",
        },
        {
          highlight: "ocaml",
          language: "ocaml",
          logoClass: "ocaml",
        },
        {
          highlight: "r",
          language: "r",
          logoClass: "r",
        },
        {
          highlight: "swift",
          language: "swift",
          logoClass: "swift",
        },
        {
          highlight: "kotlin",
          language: "kotlin",
          logoClass: "kotlin",
        },
        {
          highlight: "rust",
          language: "rust",
          logoClass: "rust",
        },
      ],
    } satisfies Preset.ThemeConfig,

  plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "openapi",
        docsPluginId: "classic",
        config: {
          offer: {
            specPath: "examples/offer.yaml",
            outputDir: "docs/reference/offer-api",
            sidebarOptions: {
              groupPathsBy: "tag",
              categoryLinkSource: "tag",
            },
            showSchemas: false,
          } satisfies OpenApiPlugin.Options,
        } satisfies Plugin.PluginOptions,
      },
    ],
    [
      "@graphql-markdown/docusaurus",
      /** @type {import('@graphql-markdown/types').ConfigOptions} */
      {
        schema: process.env.PRISM_SCHEMA_URL,
        rootPath: './docs',
        baseURL: "reference/prism",
        homePage: "./static/prism.md",
        // ... other options
        loaders: {
          UrlLoader: {
            module: "@graphql-tools/url-loader",
            options: {
              headers: {
                Authorization: 'Bearer ' + process.env.PRISM_ACCESS_TOKEN,
              }
            }
          }
        }
      },
    ],
  ],

  themes: ["docusaurus-theme-openapi-docs"],
  customFields: {
    // Prism (GraphQL) endpoint, exposed to the client-side GraphiQL playground.
    // Value still points at the targeted-api host (backend not renamed); only the
    // docs/var name is rebranded to Prism. (PUB-191, WS3)
    'PRISM_SCHEMA_URL': process.env.PRISM_SCHEMA_URL ?? 'https://targeted-api.adgem.com/v1/offers',
  },
};

export default async function createConfig() {
  return config;
}
