/**
 * Unified Sidebar Configuration
 *
 * This sidebar structure organizes all AdGem documentation into a logical hierarchy:
 * 1. Getting Started - First thing publishers see
 * 2. Integrations - All offer integration methods (APIs, SDKs, Web)
 * 3. Webhooks - Postbacks and event notifications
 * 4. Configuration - Offer wall customization
 * 5. Offers - Offer types and difficulty
 * 6. Monetization - Payment setup
 * 7. API Reference - Reporting and legacy APIs
 * 8. Resources - Branding, glossary, support
 * 9. Legal - Terms, privacy, licenses
 * 10. Player Support - End-user facing docs (different audience)
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import offersApiSidebar from './docs/integrations/offer-api/sidebar';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  mainSidebar: [
    // Getting Started - TOP PRIORITY for new publishers
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "doc",
        id: "getting-started/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },

    // Integrations - All methods to integrate offers
    {
      type: "category",
      label: "Integrations",
      collapsible: true,
      collapsed: false,
      items: [
        // Offer API (REST)
        {
          type: "category",
          label: "Offer API (REST)",
          link: {
            type: "generated-index",
            title: "Offer API",
            description: "REST API for retrieving untargeted offers from the AdGem platform.",
            slug: "/integrations/offer-api",
          },
          items: [offersApiSidebar],
        },
        // Targeted API (GraphQL)
        {
          type: "category",
          label: "Targeted API (GraphQL)",
          link: {
            type: "generated-index",
            title: "Targeted API",
            description: "GraphQL API for retrieving targeted offers from the AdGem platform.",
            slug: "/integrations/targeted-api",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "integrations/targeted-api",
            },
          ],
        },
        // iOS SDK
        {
          type: "category",
          label: "iOS SDK",
          link: {
            type: "doc",
            id: "integrations/ios-sdk/index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "integrations/ios-sdk",
            },
          ],
        },
        // Android SDK
        {
          type: "category",
          label: "Android SDK",
          link: {
            type: "doc",
            id: "integrations/android-sdk/index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "integrations/android-sdk",
            },
          ],
        },
        // Unity SDK
        {
          type: "category",
          label: "Unity SDK",
          link: {
            type: "doc",
            id: "integrations/unity-sdk/index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "integrations/unity-sdk",
            },
          ],
        },
        // Web Offerwall
        {
          type: "category",
          label: "Web Offerwall",
          link: {
            type: "doc",
            id: "integrations/web-offerwall/index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "integrations/web-offerwall",
            },
          ],
        },
      ],
    },

    // Webhooks - Postbacks and notifications
    {
      type: "category",
      label: "Webhooks",
      link: {
        type: "doc",
        id: "webhooks/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "webhooks",
        },
      ],
    },

    // Configuration
    {
      type: "category",
      label: "Configuration",
      link: {
        type: "doc",
        id: "configuration/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "configuration",
        },
      ],
    },

    // Offers
    {
      type: "category",
      label: "Offers",
      link: {
        type: "doc",
        id: "offers/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "offers",
        },
      ],
    },

    // Monetization
    {
      type: "category",
      label: "Monetization",
      link: {
        type: "doc",
        id: "monetization/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "monetization",
        },
      ],
    },

    // API Reference
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "api-reference/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api-reference",
        },
      ],
    },

    // Resources
    {
      type: "category",
      label: "Resources",
      link: {
        type: "doc",
        id: "resources/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "resources",
        },
      ],
    },

    // Legal
    {
      type: "category",
      label: "Legal",
      link: {
        type: "doc",
        id: "legal/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "legal",
        },
      ],
    },

    // Player Support - At bottom (different audience)
    {
      type: "category",
      label: "Player Support",
      link: {
        type: "doc",
        id: "player-support/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "player-support",
        },
      ],
    },
  ],
};

export default sidebars;
